In [11]:
#Pandas kutubxonasi bilan csv fayliga murojat
import pandas as pd
csv=pd.read_csv('/content/world_population.csv')
csv

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [9]:
from google.colab import files
fayl_yuklash=files.upload()

Saving world_population.csv to world_population.csv

In [12]:
#jadval boshidagi n ta strga murojat
csv.head(10)

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint John’s,North America,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03

In [15]:
#ustun nomlarini o'zgartirish
csv.rename(columns={'Capital':'Poytaxt','Continent':"Qit'a",'Country/Territory':'Davlat/Maydon'})

,Rank,CCA3,Davlat/Maydon,Poytaxt,Qit'a,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [37]:
#csv jadvaldan ustuni ajratib olish
c1=csv['Capital']
c1

0                 Kabul
1                Tirana
2               Algiers
3             Pago Pago
4      Andorra la Vella
             ...
229            Mata-Utu
230            El Aaiún
231               Sanaa
232              Lusaka
233              Harare
Name: Capital, Length: 234, dtype: object

In [32]:
 #yangi c2 ustunni ajratish
c2=csv['Area (km²)']
c2

0       652230.0
1        28748.0
2      2381741.0
3          199.0
4          468.0
         ...
229        142.0
230     266000.0
231     527968.0
232     752612.0
233     390757.0
Name: Area (km²), Length: 234, dtype: float64

In [39]:
#jadvallarni birlashtirish
c3=pd.concat([c1,c2])
c3

0                 Kabul
1                Tirana
2               Algiers
3             Pago Pago
4      Andorra la Vella
             ...
229               142.0
230            266000.0
231            527968.0
232            752612.0
233            390757.0
Length: 468, dtype: object

In [31]:
#satr indexsi bo'yicha murojat
csv.iloc[10:100:10]

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
10,198,ABW,Aruba,Oranjestad,North America,106445.0,106585.0,104257.0,100341.0,89101.0,65712.0,62267.0,59106.0,180.0,591.3611,0.9991,0.00
20,177,BLZ,Belize,Belmopan,North America,405272.0,394921.0,359871.0,322106.0,240406.0,182589.0,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
30,108,BGR,Bulgaria,Sofia,Europe,6781953.0,6979175.0,7309253.0,7592273.0,8097691.0,8767778.0,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
40,65,CHL,Chile,Santiago,South America,19603733.0,19300315.0,17870124.0,17004162.0,15351799.0,13342868.0,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
50,88,CZE,Czech Republic,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
60,132,ERI,Eritrea,Asmara,Africa,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
70,183,PYF,French Polynesia,Papeete,Oceania,306279.0,301920.0,291787.0,283788.0,250927.0,211089.0,163591.0,117891.0,4167.0,73.5011,1.0074,0.00
80,178,GLP,Guadeloupe,Basse-Terre,North America,395752.0,395642.0,399089.0,403072.0,424067.0,391951.0,334234.0,318310.0,1628.0,243.0909,0.9992,0.00
90,94,HUN,Hungary,Budapest,Europe,9967308.0,9750573.0,9844246.0,9986825.0,10202055.0,10375989.0,10698679.0,10315366.0,93028.0,107.1431,1.0265,0.12

In [40]:
#satr indexsi bo'yicha murojat
csv.iloc[100]

Rank                                     52
CCA3                                    CIV
Country/Territory               Ivory Coast
Capital                        Yamoussoukro
Continent                            Africa
2022 Population                  28160542.0
2020 Population                  26811790.0
2015 Population                  23596741.0
2010 Population                  21120042.0
2000 Population                  16799670.0
1990 Population                  11910540.0
1980 Population                   8303809.0
1970 Population                   5477086.0
Area (km²)                         322463.0
Density (per km²)                   87.3295
Growth Rate                          1.0248
World Population Percentage            0.35
Name: 100, dtype: object

In [41]:
# Satr va ustunga murojat
csv.loc[2,'Capital']

'Algiers'